spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/issues-tracker
        username: dbtester
        password: dbpassword
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MariaDB103Dialect
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp