name: Maven CI

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: issues-tracker
          MYSQL_USER: dbtester
          MYSQL_PASSWORD: dbpassword
          MYSQL_ROOT_PASSWORD: dbpassword
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Verify MariaDB connection
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
